fixtures:
  repositories:
    runit: "git://github.com/mstrauss/puppet-runit.git"
    mysql: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
    postgresql: 'git://github.com/puppetlabs/puppet-postgresql.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    concat: 'git://github.com/ripienaar/puppet-concat.git'
    nginx: 'git://github.com/BenoitCattie/puppet-nginx.git'
    rbenv: 'git://github.com/dima-exe/puppet-rbenv.git'
  symlinks:
    rails: "#{source_dir}"
