name    'dmexe-rails'
version '0.1.2'
source 'http://github.com/dima-exe/puppet-rails'
author 'Eduardo Gutierrez'
license 'MIT'
summary 'Puppet Rails deploy management'
description 'Allows you to manage your rails deploy environment'
project_page 'http://github.com/dima-exe/puppet-rails'

dependency 'puppetlabs/mysql'
dependency 'puppetlabs/postgresql'
dependency 'dmexe/rbenv'
dependency 'BenoitCattie/nginx'
